---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "post-service"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "post-service"
  namespace: "steve-overflow"
  labels:
    app: "post-service"
spec:
  selector:
    matchLabels:
      app: "post-service"
  template:
    metadata:
      labels:
        app: "post-service"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: post-config
        name: "post-service-sha256-1"
        image: "gcr.io/steveoverflow-289df/post-service:latest"
        resources:
          limits:
            cpu: "0.05"

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "post-service-hpa-yrnk"
  namespace: "steve-overflow"
  labels:
    app: "post-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "post-service"
    apiVersion: "apps/v1"
  minReplicas: 5
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 25
