name: PostService

on:
push:
branches:
- master

jobs:
build-test:
name: Go Build and Test
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

- name: Set up Go
  uses: actions/setup-go@v3
  with:
    go-version: 1.19.2

- name: Build
  run: go build -v ./...

- name: Cache Report
  uses: actions/upload-artifact@v3
  with:
    name: test-report
    path: coverage.out

push:
name: Push new container to registry
runs-on: ubuntu-latest
needs: build-test
steps:
- uses: actions/checkout@v3

deploy:
name: Deploy to Bubuntu
runs-on: [self-hosted, develop]
needs: push
steps:
- uses: actions/checkout@v3
- uses: azure/k8s-set-context@v2
id: login

- name: Create namespace
  run: |
    namespacePresent=`kubectl get namespace | grep master | wc -l`
    if [ $namespacePresent -eq 0 ]
    then
        echo `kubectl create namespace master`
    fi

# - uses: azure/k8s-deploy@v4.6
#   with:
#     namespace: release
#     manifests: |
#       manifests/rel-deployment.yml
#       manifests/service.yml
#     images: |
#       sharedacranyid.azurecr.io/mask:${{ github.sha }}
#     imagepullsecrets: |
#       sharedacranyidauth
