name: PostService

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Build
      run: go build -v ./...

  push:
    name: Push new container to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: stevenjansen
          password: dckr_pat_mNcohwOkR1oF0fYkDv7ZHzO86Rs

      - name: Build and push image to registry
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t stevenjansen/steveoverflow:postservice --label dockerfile-path=Dockerfile
          docker push stevenjansen/steveoverflow:postservice

