name: PostService

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Build
      run: go build -v ./...

    - name: Cache Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: coverage.out


push:
  name: Push new container to registry
  runs-on: ubuntu-latest
  needs: build-test
  steps:
    - uses: actions/checkout@v3